name: "Vaccine Notifier"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *" # Every 30 minutes, used https://crontab.guru/#*/30_*_*_*_*

jobs:
  bot:
    runs-on: windows-latest
    steps:
      - name: "Checkout repository content"
        uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      - name: "Install pip packages"
        uses: "BSFishy/pip-action@v1"
        # with: 
          # packages: |
            # python-dotenv
            # requests

      - name: "Running the actual code"
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: "python index.py"